# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cafa3af5a1c938dcc7eee1f1058d6dca17e020a0dc2122cadbbf835122cd38f41daa6034cee40acfe5e6e45aeef1c096740b74e23990eca57f9ddc25ff93379

test:
  secret_key_base: bf3a68da17d717d8760b89dfcfbcf7ea55adfc3071cf583c3f07319fe0688e58eec67577f95a9f5d2c82962a8f40560c5c5ee4ae04527102da29061b7c820632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
